[package]
name = "crdt-lww"
version = "0.1.0"
edition = "2021"

[lib]
name = "crdt_lww"
crate-type = ["lib"]

[features]
default = []
extension-module = ["pyo3/extension-module"]

[dependencies]
pyo3 = { version = "0.22.6", features = ["extension-module", "gil-refs", "macros"] }
dashmap = "6.1.0"
